<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DocumentSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $data = [
            [
                'id_section' => 1,
                'nama_file' => 'Bill of Lading',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/bl.pdf',
                'link_path_template_file' => 'documents/templates/bl.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Bill of Lading (B/L) adalah dokumen resmi yang diterbitkan oleh pihak pengangkut (carrier) sebagai bukti penerimaan barang untuk dikirim, yang juga memuat rincian barang, tujuan pengiriman, serta pihak pengirim dan penerima.',
                'updated_by' => 1,
                'is_internal' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_section' => 1,
                'nama_file' => 'Invoice',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/invoice.pdf',
                'link_path_template_file' => 'documents/templates/invoice.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Invoice adalah dokumen yang berisi rincian transaksi penjualan antara penjual dan pembeli, mencakup informasi barang atau jasa, jumlah, harga, serta total pembayaran yang harus dilakukan.',
                'updated_by' => 1,
                'is_internal' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_section' => 1,
                'nama_file' => 'Packing List',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/packing_list.pdf',
                'link_path_template_file' => 'documents/templates/packing_list.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Packing list adalah dokumen yang menjelaskan detail isi pengemasan barang, seperti jenis barang, jumlah, berat, ukuran, dan cara pengemasan dalam suatu pengiriman.',
                'updated_by' => 1,
                'is_internal' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_section' => 1,
                'nama_file' => 'Asuransi',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/polis_asuransi.pdf',
                'link_path_template_file' => 'documents/templates/polis_asuransi.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Asuransi adalah dokumen yang menyatakan adanya perlindungan terhadap risiko kerusakan, kehilangan, atau kejadian tertentu atas barang selama proses pengiriman, sesuai dengan ketentuan polis yang berlaku.',
                'updated_by' => 1,
                'is_internal' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_section' => 1,
                'nama_file' => 'Surat Kuasa Kepabeanan',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/sk_kepabean.pdf',
                'link_path_template_file' => 'documents/templates/sk_kepabean.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Surat Kuasa Kepabeanan adalah dokumen yang memberikan wewenang dari pemilik barang kepada pihak lain (biasanya perusahaan jasa kepabeanan atau forwarder) untuk mengurus proses administrasi dan formalitas di bea cukai.',
                'updated_by' => 1,
                'is_internal' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_section' => 2,
                'nama_file' => 'Surat Kuasa release DO',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/dokumen_1.pdf',
                'link_path_template_file' => 'documents/templates/dokumen_1.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Surat Kuasa release DO adalah dokumen yang menyatakan persetujuan atau otorisasi untuk mengeluarkan Delivery Order (DO), sehingga barang dapat diambil dari pihak pengangkut atau gudang setelah semua persyaratan terpenuhi.',
                'updated_by' => 1,
                'is_internal' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_section' => 2,
                'nama_file' => 'Surat Pinjam Container',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/dokumen_2.pdf',
                'link_path_template_file' => 'documents/templates/dokumen_2.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Surat Pinjam Container adalah dokumen yang menyatakan peminjaman kontainer dari pihak pelayaran kepada pengguna (shipper/consignee) dalam pengiriman Full Container Load (FCL), yang berisi ketentuan penggunaan serta tanggung jawab atas kontainer tersebut selama masa peminjaman.',
                'updated_by' => 1,
                'is_internal' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_section' => 2,
                'nama_file' => 'Invoice DO',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/dokumen_2.pdf',
                'link_path_template_file' => 'documents/templates/dokumen_2.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Invoice DO adalah dokumen tagihan yang diterbitkan oleh pihak pelayaran atau agen terkait biaya pengeluaran Delivery Order, yang mencakup rincian biaya administrasi atau layanan yang harus dibayar sebelum DO dapat digunakan.',
                'updated_by' => 1,
                'is_internal' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_section' => 3,
                'nama_file' => 'Draft PIB/PEB',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/draft_pib.pdf',
                'link_path_template_file' => 'documents/templates/draft_pib.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Draft PIB (Pemberitahuan Impor Barang) adalah Dokumen versi awal dari PIB atau PEB yang masih dalam tahap penyusunan atau pengecekan, biasanya belum final dan masih dapat mengalami perubahan sebelum diajukan secara resmi.',
                'updated_by' => 1,
                'is_internal' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_section' => 3,
                'nama_file' => 'PIB/PEB Confirm',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/pib_final.pdf',
                'link_path_template_file' => 'documents/templates/pib_final.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'PIB Final (Pemberitahuan Impor Barang Final) adalah Dokumen PIB atau PEB yang telah diverifikasi dan disetujui untuk diajukan atau sudah resmi terdaftar dalam sistem kepabeanan, sehingga data di dalamnya dianggap final.',
                'updated_by' => 1,
                'is_internal' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_section' => 4,
                'nama_file' => 'Id Billing',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/id_billing.pdf',
                'link_path_template_file' => 'documents/templates/id_billing.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Id Billing adalah Kode identifikasi unik yang diterbitkan oleh sistem kepabeanan atau perpajakan sebagai referensi pembayaran kewajiban negara (seperti bea masuk, pajak, atau pungutan lainnya) atas suatu transaksi.',
                'updated_by' => 1,
                'is_internal' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_section' => 4,
                'nama_file' => 'Bukti Penerimaan Negara',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/bukti_pembayaran.pdf',
                'link_path_template_file' => 'documents/templates/bukti_pembayaran.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Bukti Penerimaan Negara adalah dokumen resmi yang menyatakan bahwa pembayaran kepada negara telah diterima dan tercatat, biasanya berisi detail transaksi pembayaran seperti jumlah, tanggal, dan kode referensi (ID Billing).',
                'updated_by' => 1,
                'is_internal' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_section' => 5,
                'nama_file' => 'PIB/PEB NOPEN',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/sppb.pdf',
                'link_path_template_file' => 'documents/templates/sppb.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'PIB/PEB NOPEN adalah nomor resmi yang diberikan oleh sistem kepabeanan setelah dokumen PIB (impor) atau PEB (ekspor) didaftarkan, sebagai identitas unik atas dokumen tersebut dalam proses administrasi bea cukai.',
                'updated_by' => 1,
                'is_internal' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_section' => 5,
                'nama_file' => 'SPJM/PPB',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/sppb.pdf',
                'link_path_template_file' => 'documents/templates/sppb.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'SPJM/PPB adalah dokumen yang menunjukkan bahwa barang impor/ekspor ditetapkan masuk jalur pemeriksaan fisik oleh bea cukai.',
                'updated_by' => 1,
                'is_internal' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_section' => 5,
                'nama_file' => 'SPPB/NPE',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/sppb.pdf',
                'link_path_template_file' => 'documents/templates/sppb.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'SPPB/NPE adalah Dokumen yang menyatakan bahwa barang impor/ekspor telah mendapatkan izin untuk dikeluarkan dari kawasan pabean.',
                'updated_by' => 1,
                'is_internal' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Kosongkan tabel terlebih dahulu untuk menghindari duplikasi data saat seeding ulang
        DB::connection('tako-user')->table('master_documents')->truncate();

        // Insert data baru
        DB::connection('tako-user')->table('master_documents')->insert($data);
    }
}