<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TenantDocumentSeeder extends Seeder
{
    /**
     * Seed the master_documents_trans table in the TENANT database.
     * This seeds the document templates per company into their tenant DB.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $data = [
            [
                'id_section' => 1,
                'nama_file' => 'Bill of Lading',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/bl.pdf',
                'link_path_template_file' => 'documents/templates/bl.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Bill of Lading (B/L) adalah dokumen resmi yang diterbitkan oleh pihak pengangkut (carrier) sebagai bukti penerimaan barang untuk dikirim, yang juga memuat rincian barang, tujuan pengiriman, serta pihak pengirim dan penerima.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 1,
                'nama_file' => 'Invoice',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/invoice.pdf',
                'link_path_template_file' => 'documents/templates/invoice.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Invoice adalah dokumen yang berisi rincian transaksi penjualan antara penjual dan pembeli, mencakup informasi barang atau jasa, jumlah, harga, serta total pembayaran yang harus dilakukan.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 1,
                'nama_file' => 'Packing List',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/packing_list.pdf',
                'link_path_template_file' => 'documents/templates/packing_list.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Packing list adalah dokumen yang menjelaskan detail isi pengemasan barang, seperti jenis barang, jumlah, berat, ukuran, dan cara pengemasan dalam suatu pengiriman.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 1,
                'nama_file' => 'Asuransi',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/asuransi.pdf',
                'link_path_template_file' => 'documents/templates/asuransi.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Asuransi adalah dokumen perjanjian antara dua pihak, di mana satu pihak (perusahaan asuransi) memberikan perlindungan finansial kepada pihak lain (tertanggung) terhadap risiko tertentu, dengan imbalan premi (biaya yang dibayar secara berkala). asuransi digunakan untuk melindungi barang selama pengiriman dari risiko seperti: Kerusakan, Kehilangan, Kecelakaan saat transportasi',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 1,
                'nama_file' => 'Surat Kuasa Kepabeanan',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/sk_kepabean.pdf',
                'link_path_template_file' => 'documents/templates/sk_kepabean.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Surat Kuasa Kepabeanan adalah dokumen yang memberikan wewenang dari pemilik barang kepada pihak lain (biasanya perusahaan jasa kepabeanan atau forwarder) untuk mengurus proses administrasi dan formalitas di bea cukai.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 1,
                'nama_file' => 'Persetujuan Impor',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/pi.pdf',
                'link_path_template_file' => 'documents/templates/pi.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Persetujuan Impor (PI) adalah dokumen yang merupakan izin resmi dari pemerintah yang wajib dimiliki oleh importir untuk memasukkan barang tertentu dari luar negeri ke Indonesia.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 1,
                'nama_file' => 'Laporan Surveyor',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/L/S.pdf',
                'link_path_template_file' => 'documents/templates/L/S.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Laporan Surveyor (L/S) adalah dokumen verifikasi resmi atau dokumen hasil pemeriksaan barang oleh surveyor untuk memastikan barang yang di impor sesuai dengan aturan yang berlaku sebelum barang tersebut masuk ke Indonesia.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 1,
                'nama_file' => 'Sales Contract / Purchase Order',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/SC-PO.pdf',
                'link_path_template_file' => 'documents/templates/SC-PO.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Sales Contract / Purchase Order adalah Dokumen yang digunakan sebagai dasar informasi transaksi jual beli antara penjual dan pembeli, yang memuat rincian barang, jumlah, harga, serta pihak-pihak yang terlibat, dan dapat berupa kontrak penjualan atau dokumen pemesanan yang mewakili kesepakatan atau permintaan pembelian.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 1,
                'nama_file' => 'Weight Certificate',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/wc.pdf',
                'link_path_template_file' => 'documents/templates/wc.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Weight Certificate adalah Dokumen resmi yang menyatakan hasil penimbangan barang, yang memuat informasi mengenai berat bersih, berat kotor, dan/atau berat lainnya sesuai hasil pengukuran yang dilakukan oleh pihak berwenang atau lembaga yang ditunjuk.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 1,
                'nama_file' => 'Product Catalog',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/pc.pdf',
                'link_path_template_file' => 'documents/templates/pc.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Product Catalog adalah Dokumen yang berisi informasi mengenai produk yang diperdagangkan, mencakup deskripsi barang, spesifikasi, jenis, serta karakteristik produk yang digunakan sebagai referensi untuk mengidentifikasi barang tersebut.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 1,
                'nama_file' => 'Surat Kuasa BC',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/SK_BC.pdf',
                'link_path_template_file' => 'documents/templates/SK_BC.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Surat Kuasa BC adalah Dokumen yang berisi pemberian wewenang dari pemilik barang kepada pihak lain untuk mewakili dan melakukan pengurusan administrasi serta proses kepabeanan di instansi bea cukai.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 1,
                'nama_file' => 'Surat Pernyataan Surrender',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/SK_BC.pdf',
                'link_path_template_file' => 'documents/templates/SK_BC.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Surat Pernyataan Surrender adalah Dokumen pernyataan resmi dari pihak terkait yang menyatakan pelepasan atau penyerahan hak atas suatu dokumen atau kewenangan tertentu, sehingga dokumen atau hak tersebut tidak lagi digunakan dan proses selanjutnya dapat dilakukan sesuai ketentuan yang berlaku.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 2,
                'nama_file' => 'Surat Kuasa Release DO',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/dokumen_1.pdf',
                'link_path_template_file' => 'documents/templates/dokumen_1.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Surat Kuasa release DO adalah dokumen yang menyatakan persetujuan atau otorisasi untuk mengeluarkan Delivery Order (DO), sehingga barang dapat diambil dari pihak pengangkut atau gudang setelah semua persyaratan terpenuhi.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 2,
                'nama_file' => 'Surat Pinjam Container',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/dokumen_2.pdf',
                'link_path_template_file' => 'documents/templates/dokumen_2.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Surat Pinjam Container adalah dokumen yang menyatakan peminjaman kontainer dari pihak pelayaran kepada pengguna (shipper/consignee) dalam pengiriman Full Container Load (FCL), yang berisi ketentuan penggunaan serta tanggung jawab atas kontainer tersebut selama masa peminjaman.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 2,
                'nama_file' => 'Invoice DO',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/dokumen_2.pdf',
                'link_path_template_file' => 'documents/templates/dokumen_2.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Invoice DO adalah dokumen tagihan yang diterbitkan oleh pihak pelayaran atau agen terkait biaya pengeluaran Delivery Order, yang mencakup rincian biaya administrasi atau layanan yang harus dibayar sebelum DO dapat digunakan.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 0,
            ],
            [
                'id_section' => 3,
                'nama_file' => 'Draft PIB/PEB',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/draft_pib.pdf',
                'link_path_template_file' => 'documents/templates/draft_pib.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Draft PIB (Pemberitahuan Impor Barang) adalah Dokumen versi awal dari PIB atau PEB yang masih dalam tahap penyusunan atau pengecekan, biasanya belum final dan masih dapat mengalami perubahan sebelum diajukan secara resmi.',
                'updated_by' => 1,
                'is_internal' => true,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now, 
                'is_confirmed' => 1,
                'is_print' => 0,
            ],
            [
                'id_section' => 3,
                'nama_file' => 'PIB/PEB Confirm',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/pib_final.pdf',
                'link_path_template_file' => 'documents/templates/pib_final.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'PIB/PEB Confirm adalah Dokumen PIB atau PEB yang telah diverifikasi dan disetujui untuk diajukan atau sudah resmi terdaftar dalam sistem kepabeanan, sehingga data di dalamnya dianggap final.',
                'updated_by' => 1,
                'is_internal' => true,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 0,
            ],
            [
                'id_section' => 4,
                'nama_file' => 'Id Billing',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/id_billing.pdf',
                'link_path_template_file' => 'documents/templates/id_billing.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Id Billing adalah Kode identifikasi unik yang diterbitkan oleh sistem kepabeanan atau perpajakan sebagai referensi pembayaran kewajiban negara (seperti bea masuk, pajak, atau pungutan lainnya) atas suatu transaksi.',
                'updated_by' => 1,
                'is_internal' => true,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 1,
                'is_print' => 0,
            ],
            [
                'id_section' => 4,
                'nama_file' => 'Bukti Penerimaan Negara',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/bukti_pembayaran.pdf',
                'link_path_template_file' => 'documents/templates/bukti_pembayaran.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Bukti Penerimaan Negara adalah dokumen resmi yang menyatakan bahwa pembayaran kepada negara telah diterima dan tercatat, biasanya berisi detail transaksi pembayaran seperti jumlah, tanggal, dan kode referensi (ID Billing).',
                'updated_by' => 1,
                'is_internal' => true,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 0,
            ],
            [
                'id_section' => 4,
                'nama_file' => 'Surat Perintah Pemindahan Media Pembawa (SP2MP)',
                'attribute' => 0, //non mandatory (walaupun di data master yangh diinput mandatory)
                'link_path_example_file' => 'documents/examples/SP2MP.pdf',
                'link_path_template_file' => 'documents/templates/SP2MP.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Surat Perintah Pemindahan Media Pembawa (SP2MP) adalah Dokumen resmi Badan Karantina Indonesia yang memerintahkan pemindahan media pembawa (hewan, tumbuhan, ikan) dari terminal bongkar ke Tempat Pemeriksaan Karantina (TPK) untuk pemeriksaan lebih lanjut',
                'updated_by' => 1,
                'is_internal' => true,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 0,
            ],
            [
                'id_section' => 5,
                'nama_file' => 'PIB/PEB NOPEN Stamp',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/sppb.pdf',
                'link_path_template_file' => 'documents/templates/sppb.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'PIB/PEB NOPEN Stamp adalah nomor resmi yang diberikan oleh sistem kepabeanan setelah dokumen PIB (impor) atau PEB (ekspor) didaftarkan, sebagai identitas unik atas dokumen tersebut dalam proses administrasi bea cukai.',
                'updated_by' => 1,
                'is_internal' => true,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 0,
            ],
            [
                'id_section' => 5,
                'nama_file' => 'PIB/PEB NOPEN Non Stamp',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/sppb.pdf',
                'link_path_template_file' => 'documents/templates/sppb.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'PIB/PEB NOPEN Non Stamp adalah Dokumen yang menunjukkan nomor pendaftaran (NOPEN) atas PIB/PEB yang telah diterbitkan oleh sistem kepabeanan, namun belum dilengkapi dengan cap/stempel resmi sebagai tanda validasi fisik atau pengesahan tambahan dari pihak terkait.',
                'updated_by' => 1,
                'is_internal' => true,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 0,
            ],
            [
                'id_section' => 5,
                'nama_file' => 'SPJM/PPB',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/sppb.pdf',
                'link_path_template_file' => 'documents/templates/sppb.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'SPJM/PPB adalah dokumen yang menunjukkan bahwa barang impor/ekspor ditetapkan masuk jalur pemeriksaan fisik oleh bea cukai.',
                'updated_by' => 1,
                'is_internal' => true,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 0,
            ],
            [
                'id_section' => 5,
                'nama_file' => 'SPPB/NPE',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/sppb.pdf',
                'link_path_template_file' => 'documents/templates/sppb.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'SPPB/NPE adalah Dokumen yang menyatakan bahwa barang impor/ekspor telah mendapatkan izin untuk dikeluarkan dari kawasan pabean.',
                'updated_by' => 1,
                'is_internal' => true,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 0,
            ],
            [
                'id_section' => 6,
                'nama_file' => 'Additional Memo',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/additional_memo.pdf',
                'link_path_template_file' => 'documents/templates/additional_memo.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Memo tambahan untuk dokumen pendukung lainnya.',
                'updated_by' => 1,
                'is_internal' => true,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 0,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'Sertifikat Fumigasi',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/sertifikat_fumigasi.pdf',
                'link_path_template_file' => 'documents/templates/sertifikat_fumigasi.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Sertifikat Fumigasi adalah dokumen yang menyatakan bahwa suatu barang (biasanya berbahan kayu atau produk pertanian) telah dilakukan proses fumigasi (pengasapan) untuk membunuh hama, serangga, atau organisme pengganggu.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'Packing Declaration',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/packing_declaration.pdf',
                'link_path_template_file' => 'documents/templates/packing_declaration.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Packing Declaration adalah surat pernyataan dari eksportir yang menjelaskan jenis bahan kemasan yang digunakan dalam pengiriman barang.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'Prior Notice',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/prior_notice.pdf',
                'link_path_template_file' => 'documents/templates/prior_notice.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Prior Notice adalah pemberitahuan awal yang wajib disampaikan ke otoritas negara tujuan sebelum barang dikirim, terutama untuk produk tertentu seperti makanan/ Bahan Baku Pakan.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'S-Kep 142',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/S-Kep 142.pdf',
                'link_path_template_file' => 'documents/templates/S-Kep 142.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'S-Kep 142 merujuk pada Surat Keputusan Dirjen Bea dan Cukai No. 142 yang mengatur tentang tata laksana impor tertentu (umumnya terkait fasilitas atau ketentuan khusus).',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 0,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'Rekomendasi Menteri Pertanian',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/menteri_pertanian.pdf',
                'link_path_template_file' => 'documents/templates/menteri_pertanian.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Rekomendasi menteri Pertanian adalah dokumen resmi dari Kementerian Pertanian Republik Indonesia yang memberikan izin/rekomendasi untuk impor bahan tertentu yang berkaitan dengan sektor pertanian.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'Rekomendasi Menteri Perikanan',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/menteri_perikanan.pdf',
                'link_path_template_file' => 'documents/templates/menteri_perikanan.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Rekomendasi menteri Perikanan dikeluarkan oleh Kementerian Kelautan dan Perikanan Republik Indonesia untuk impor yang berkaitan dengan sektor perikanan.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'Pernyataan Keterlambatan Muat Kapal',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/pernyataan_keterlambatan.pdf',
                'link_path_template_file' => 'documents/templates/pernyataan_keterlambatan.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Pernyataan Keterlambatan Muat Kapal adalah dokumen resmi yang dibuat oleh pihak terkait (eksportir, importir, atau Shipper) untuk menjelaskan dan menyatakan secara tertulis adanya keterlambatan dalam proses pemuatan barang ke atas kapal (vessel) dari jadwal yang telah ditentukan.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'Perka',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/Perka.pdf',
                'link_path_template_file' => 'documents/templates/Perka.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Perka adalah dokumen yang berisikan aturan teknis dari kepala lembaga yang digunakan sebagai pedoman pelaksanaan suatu kebijakan impor.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 0,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'SKEP 41',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/SKEP_41.pdf',
                'link_path_template_file' => 'documents/templates/SKEP_41.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'SKEP 41 adalah singkatan dari Surat Keputusan Direktur Jenderal Bea dan Cukai Nomor KEP-41/BC/1999; merupakan dokumen yang berisikan peraturan dari Direktorat Jenderal Bea dan Cukai yang mengatur tentang Tata laksana kepabeanan di bidang impor, dan menjadi aturan teknis kepabeanan impor dari Bea Cukai yang menjadi dasar prosedur impor di Indonesia, terutama terkait proses dan dokumen impor.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 0,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'Certificate Halal',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/certificate_halal.pdf',
                'link_path_template_file' => 'documents/templates/certificate_halal.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Certificate Halal adalah dokumen yang menjamin seluruh proses produksi sesuai syariat Islam; kini wajib melalui BPJPH (Badan Penyelenggara Jaminan Produk Halal) dengan aturan terbaru bahwa produk luar negeri harus berasal dari lembaga halal yang sudah melakukan MRA (kerjasama pengakuan saling terima) dengan pemerintah Indonesia.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'SKEP 26',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/SKEP_26.pdf',
                'link_path_template_file' => 'documents/templates/SKEP_26.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'SKEP 26 adalah singkatan dari Surat Keputusan Direktur Jenderal Bea dan Cukai Nomor KEP-26/BC/1999., SKEP 26 merupakan dokumen yang berisikan aturan teknis kepabeanan untuk kegiatan ekspor yang dikeluarkan oleh Bea Cukai',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 0,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'Certificate of Origin (COO) Fasilitas',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/coo.pdf',
                'link_path_template_file' => 'documents/templates/coo.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Certificate of Origin (COO) Fasilitas adalah Dokumen asal barang yang digunakan untuk memperoleh fasilitas atau preferensi tertentu berdasarkan perjanjian perdagangan (seperti pembebasan atau pengurangan bea masuk), yang membuktikan bahwa barang berasal dari negara yang memiliki kesepakatan tersebut.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'Certificate of Origin (COO) Non Fasilitas',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/coo.pdf',
                'link_path_template_file' => 'documents/templates/coo.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Certificate of Origin (COO) Non Fasilitas adalah Dokumen asal barang yang hanya berfungsi sebagai bukti negara asal barang tanpa terkait dengan pemberian fasilitas atau preferensi tarif, dan digunakan untuk keperluan administrasi, regulasi, atau persyaratan umum lainnya.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'Certificate of Analysis (COA)',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/coa.pdf',
                'link_path_template_file' => 'documents/templates/coa.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Certificate of Analysis (COA) adalah dokumen otentik berisi hasil pengujian laboratorium yang mencantumkan kadar, komposisi, serta karakteristik fisik/kimia produk, dokumen ini wajib disertakan untuk bahan baku pangan, kimia, dan farmasi guna memastikan isinya sesuai dengan klaim pada label.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'Phytosanitary Certificate (Phyto)',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/Phyto.pdf',
                'link_path_template_file' => 'documents/templates/Phyto.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Phytosanitary Certificate (Phyto) adalah dokumen jaminan kesehatan tumbuhan yang diterbitkan oleh otoritas karantina negara asal; dokumen ini wajib ada untuk memastikan komoditas nabati tidak membawa OPTK (Organisme Pengganggu Tumbuhan Karantina) yang dapat merusak ekosistem pertanian di Indonesia.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'Health Certificate (HC)',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/HC.pdf',
                'link_path_template_file' => 'documents/templates/HC.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Health Certificate (HC) adalah sertifikat kesehatan untuk produk hewani atau hasil perikanan yang menyatakan bahwa produk tersebut bebas dari kontaminasi bakteri berbahaya dan wabah penyakit hewan (seperti PMK atau Flu Burung).',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'Depkes',
                'attribute' => 0,
                'link_path_example_file' => 'documents/examples/Depkes.pdf',
                'link_path_template_file' => 'documents/templates/Depkes.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Depkes (Izin Edar BPOM/Kemenkes) adalah nomor registrasi resmi yang menunjukkan bahwa produk (makanan, obat, kosmetik, atau alat kesehatan) telah lulus uji keamanan dan mutu; saat ini pendaftarannya terintegrasi melalui sistem OSS RBA, di mana tingkat risiko produk menentukan ketatnya proses verifikasi',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 1,
            ],
            [
                'id_section' => 7,
                'nama_file' => 'Setifikat Pelepasan',
                'attribute' => 1,
                'link_path_example_file' => 'documents/examples/Setifikat_Pelepasan.pdf',
                'link_path_template_file' => 'documents/templates/Setifikat_Pelepasan.pdf',
                'link_url_video_file' => 'https://www.youtube.com/watch?v=28whxoWAzA0',
                'description_file' => 'Sertifikat Pelepasan adalah dokumen resmi yang diterbitkan oleh Petugas Karantina (hewan, ikan, atau tumbuhan) yang menyatakan bahwa media pembawa (komoditas) telah diperiksa, memenuhi syarat sanitasi/fitosanitasi, dan bebas dari hama atau penyakit, sehingga aman untuk dilalulintaskan masuk/keluar wilayah Indonesia.',
                'updated_by' => 1,
                'is_internal' => false,
                'is_verification' => true,
                'created_at' => $now,
                'updated_at' => $now,
                'is_confirmed' => 0, 
                'is_print' => 0,
            ],
        ];

        // Seed into current tenant connection (tenant DB, NOT central)
        try {
            DB::connection('tenant')->statement('TRUNCATE TABLE master_documents_trans RESTART IDENTITY CASCADE');
        } catch (\Exception $e) {
            DB::connection('tenant')->table('master_documents_trans')->delete();
        }

        DB::connection('tenant')->table('master_documents_trans')->insert($data);
    }
}
