<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="UTF-8">
    <title>Data Customer</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.6;
            color: #333;
        }

        h1 {
            text-align: center;
            font-size: 20px;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            text-align: left;
            padding: 6px 10px;
            border: 1px solid #ccc;
        }

        /* Tambahkan aturan rasio 1:2 */
        .info-table td:first-child {
            width: 20%;
        }

        .info-table td:last-child {
            width: 80%;
        }

        .section-title {
            background-color: #f0f0f0;
            font-weight: bold;
            padding: 8px 10px;
        }

        .attachment-list {
            margin-top: 20px;
        }

        .attachment-list ul {
            padding-left: 20px;
        }
    </style>
</head>

<body>
    <div style="position: absolute; top: 10px; right: 20px; font-size: 12px; font-weight: bold;">
        ISO-{{ str_pad($customer->id, 5, '0', STR_PAD_LEFT) }}
    </div>
    <h1>Data Customer</h1>
    <h2 style="text-align: center; margin-top: -10px;">{{ $customer->perusahaan->nama_perusahaan ?? '-' }}</h2>

    <table class="info-table">
        <tr>
            <th class="section-title" colspan="2">Informasi Umum</th>
        </tr>
        <tr>
            <td>Kategori Usaha</td>
            <td>{{ $customer->kategori_usaha }}</td>
        </tr>
        <tr>
            <td>Nama Perusahaan</td>
            <td>{{ $customer->nama_perusahaan }}</td>
        </tr>
        <tr>
            <td>Bentuk Badan Usaha</td>
            <td>{{ $customer->bentuk_badan_usaha }}</td>
        </tr>
        <tr>
            <td>Alamat</td>
            <td>{{ $customer->alamat_lengkap }}</td>
        </tr>
        <tr>
            <td>Kota</td>
            <td>{{ $customer->kota }}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{ $customer->email }}</td>
        </tr>
        <tr>
            <td>No. Telepon Perusahaan</td>
            <td>{{ $customer->no_telp }}</td>
        </tr>
        <tr>
            <td>No. Fax</td>
            <td>{{ $customer->no_fax ?? '-'}}</td>
        </tr>
        <tr>
            <td>Website</td>
            <td>{{ $customer->website ?? '-'}}</td>
        </tr>
        <tr>
            <td>Status Perpajakan</td>
            <td>{{ $customer->status_perpajakan }}</td>
        </tr>
        <tr>
            <td>No NPWP</td>
            <td>{{ $customer->no_npwp }}</td>
        </tr>
        <tr>
            <td>No NPWP 16 Digit</td>
            <td>{{ $customer->no_npwp_16 }}</td>
        </tr>
    </table>

    <table class="info-table">
        <tr>
            <th class="section-title" colspan="2">Penanggung Jawab</th>
        </tr>
        <tr>
            <td>Nama PJ</td>
            <td>{{ $customer->nama_pj }}</td>
        </tr>
        <tr>
            <td>No. KTP PJ</td>
            <td>{{ $customer->no_ktp_pj }}</td>
        </tr>
        <tr>
            <td>No. Telepon PJ</td>
            <td>{{ $customer->no_telp_pj }}</td>
        </tr>
    </table>

    <table class="info-table">
        <tr>
            <th class="section-title" colspan="2">Personal yang dihubungi</th>
        </tr>
        <tr>
            <td>Nama</td>
            <td>{{ $customer->nama_personal }}</td>
        </tr>
        <tr>
            <td>Jabatan</td>
            <td>{{ $customer->jabatan_personal }}</td>
        </tr>
        <tr>
            <td>No. Telepon</td>
            <td>{{ $customer->no_telp_personal }}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{ $customer->email_personal }}</td>
        </tr>
    </table>

    <!-- <div class="attachment-list">
        <h3>Lampiran Dokumen</h3>
        <ul>
            @foreach ($customer->attachments as $attachment)
            <li>
                {{ strtoupper($attachment->type) }}:
                <a href="{{ route('secure.attachment.show', basename($attachment->path)) }}">
                    {{ $attachment->nama_file }}
                </a>
            </li>
            @endforeach
        </ul>
    </div> -->
    <p><small>Generated by {{ $generated_by }} on {{ now()->format('d M Y') }} at {{ now()->format('H:i') }} WIB</small></p>
</body>

</html>